language: go

go:
  - 1.4.3
  - 1.5.2
  - 1.7
  - tip

before_install:
    - uname -a
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go get github.com/funny/utest

install:
    - go get -d -v . && go build -v .

script:
    - go test -v -covermode=count -coverprofile=profile.cov

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
    - go test -race -benchmem -bench .
